// Code generated by MockGen. DO NOT EDIT.
// Source: api.go
//
// Generated by this command:
//
//	mockgen -source api.go -destination mock_api.go -package ethapi
//

// Package ethapi is a generated GoMock package.
package ethapi

import (
	context "context"
	reflect "reflect"

	common "github.com/zircuit-labs/l2-geth/common"
	consensus "github.com/zircuit-labs/l2-geth/consensus"
	slsapi "github.com/zircuit-labs/l2-geth/core/sls-common/slsapi"
	types "github.com/zircuit-labs/l2-geth/core/types"
	params "github.com/zircuit-labs/l2-geth/params"
	rpc "github.com/zircuit-labs/l2-geth/rpc"
	gomock "go.uber.org/mock/gomock"
)

// MockChainContextBackend is a mock of ChainContextBackend interface.
type MockChainContextBackend struct {
	ctrl     *gomock.Controller
	recorder *MockChainContextBackendMockRecorder
	isgomock struct{}
}

// MockChainContextBackendMockRecorder is the mock recorder for MockChainContextBackend.
type MockChainContextBackendMockRecorder struct {
	mock *MockChainContextBackend
}

// NewMockChainContextBackend creates a new mock instance.
func NewMockChainContextBackend(ctrl *gomock.Controller) *MockChainContextBackend {
	mock := &MockChainContextBackend{ctrl: ctrl}
	mock.recorder = &MockChainContextBackendMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChainContextBackend) EXPECT() *MockChainContextBackendMockRecorder {
	return m.recorder
}

// ChainConfig mocks base method.
func (m *MockChainContextBackend) ChainConfig() *params.ChainConfig {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChainConfig")
	ret0, _ := ret[0].(*params.ChainConfig)
	return ret0
}

// ChainConfig indicates an expected call of ChainConfig.
func (mr *MockChainContextBackendMockRecorder) ChainConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChainConfig", reflect.TypeOf((*MockChainContextBackend)(nil).ChainConfig))
}

// Engine mocks base method.
func (m *MockChainContextBackend) Engine() consensus.Engine {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Engine")
	ret0, _ := ret[0].(consensus.Engine)
	return ret0
}

// Engine indicates an expected call of Engine.
func (mr *MockChainContextBackendMockRecorder) Engine() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Engine", reflect.TypeOf((*MockChainContextBackend)(nil).Engine))
}

// HeaderByNumber mocks base method.
func (m *MockChainContextBackend) HeaderByNumber(arg0 context.Context, arg1 rpc.BlockNumber) (*types.Header, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HeaderByNumber", arg0, arg1)
	ret0, _ := ret[0].(*types.Header)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HeaderByNumber indicates an expected call of HeaderByNumber.
func (mr *MockChainContextBackendMockRecorder) HeaderByNumber(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HeaderByNumber", reflect.TypeOf((*MockChainContextBackend)(nil).HeaderByNumber), arg0, arg1)
}

// MockReceiptGetter is a mock of ReceiptGetter interface.
type MockReceiptGetter struct {
	ctrl     *gomock.Controller
	recorder *MockReceiptGetterMockRecorder
	isgomock struct{}
}

// MockReceiptGetterMockRecorder is the mock recorder for MockReceiptGetter.
type MockReceiptGetterMockRecorder struct {
	mock *MockReceiptGetter
}

// NewMockReceiptGetter creates a new mock instance.
func NewMockReceiptGetter(ctrl *gomock.Controller) *MockReceiptGetter {
	mock := &MockReceiptGetter{ctrl: ctrl}
	mock.recorder = &MockReceiptGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReceiptGetter) EXPECT() *MockReceiptGetterMockRecorder {
	return m.recorder
}

// GetReceipts mocks base method.
func (m *MockReceiptGetter) GetReceipts(ctx context.Context, hash common.Hash) (types.Receipts, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReceipts", ctx, hash)
	ret0, _ := ret[0].(types.Receipts)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReceipts indicates an expected call of GetReceipts.
func (mr *MockReceiptGetterMockRecorder) GetReceipts(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReceipts", reflect.TypeOf((*MockReceiptGetter)(nil).GetReceipts), ctx, hash)
}

// MockSLSQuarantineVerifier is a mock of SLSQuarantineVerifier interface.
type MockSLSQuarantineVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockSLSQuarantineVerifierMockRecorder
	isgomock struct{}
}

// MockSLSQuarantineVerifierMockRecorder is the mock recorder for MockSLSQuarantineVerifier.
type MockSLSQuarantineVerifierMockRecorder struct {
	mock *MockSLSQuarantineVerifier
}

// NewMockSLSQuarantineVerifier creates a new mock instance.
func NewMockSLSQuarantineVerifier(ctrl *gomock.Controller) *MockSLSQuarantineVerifier {
	mock := &MockSLSQuarantineVerifier{ctrl: ctrl}
	mock.recorder = &MockSLSQuarantineVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSLSQuarantineVerifier) EXPECT() *MockSLSQuarantineVerifierMockRecorder {
	return m.recorder
}

// IsQuarantined mocks base method.
func (m *MockSLSQuarantineVerifier) IsQuarantined(ctx context.Context, txHash common.Hash) (*slsapi.IsQuarantinedResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsQuarantined", ctx, txHash)
	ret0, _ := ret[0].(*slsapi.IsQuarantinedResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsQuarantined indicates an expected call of IsQuarantined.
func (mr *MockSLSQuarantineVerifierMockRecorder) IsQuarantined(ctx, txHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsQuarantined", reflect.TypeOf((*MockSLSQuarantineVerifier)(nil).IsQuarantined), ctx, txHash)
}
