// Code generated by MockGen. DO NOT EDIT.
// Source: stray.go
//
// Generated by this command:
//
//	mockgen -source stray.go -destination mock_stray.go -package slsstray
//

// Package slsstray is a generated GoMock package.
package slsstray

import (
	context "context"
	reflect "reflect"

	sls "github.com/zircuit-labs/l2-geth/core/sls-common"
	model "github.com/zircuit-labs/l2-geth/core/sls-common/model"
	gomock "go.uber.org/mock/gomock"
)

// MockmetadataGenerator is a mock of metadataGenerator interface.
type MockmetadataGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockmetadataGeneratorMockRecorder
	isgomock struct{}
}

// MockmetadataGeneratorMockRecorder is the mock recorder for MockmetadataGenerator.
type MockmetadataGeneratorMockRecorder struct {
	mock *MockmetadataGenerator
}

// NewMockmetadataGenerator creates a new mock instance.
func NewMockmetadataGenerator(ctrl *gomock.Controller) *MockmetadataGenerator {
	mock := &MockmetadataGenerator{ctrl: ctrl}
	mock.recorder = &MockmetadataGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmetadataGenerator) EXPECT() *MockmetadataGeneratorMockRecorder {
	return m.recorder
}

// NewMetadata mocks base method.
func (m *MockmetadataGenerator) NewMetadata() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewMetadata")
	ret0, _ := ret[0].(error)
	return ret0
}

// NewMetadata indicates an expected call of NewMetadata.
func (mr *MockmetadataGeneratorMockRecorder) NewMetadata() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewMetadata", reflect.TypeOf((*MockmetadataGenerator)(nil).NewMetadata))
}

// StoreInFS mocks base method.
func (m *MockmetadataGenerator) StoreInFS(metadata *MetadataFile, fname LocalStorageFileName) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StoreInFS", metadata, fname)
	ret0, _ := ret[0].(error)
	return ret0
}

// StoreInFS indicates an expected call of StoreInFS.
func (mr *MockmetadataGeneratorMockRecorder) StoreInFS(metadata, fname any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StoreInFS", reflect.TypeOf((*MockmetadataGenerator)(nil).StoreInFS), metadata, fname)
}

// MockdiffGenerator is a mock of diffGenerator interface.
type MockdiffGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockdiffGeneratorMockRecorder
	isgomock struct{}
}

// MockdiffGeneratorMockRecorder is the mock recorder for MockdiffGenerator.
type MockdiffGeneratorMockRecorder struct {
	mock *MockdiffGenerator
}

// NewMockdiffGenerator creates a new mock instance.
func NewMockdiffGenerator(ctrl *gomock.Controller) *MockdiffGenerator {
	mock := &MockdiffGenerator{ctrl: ctrl}
	mock.recorder = &MockdiffGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdiffGenerator) EXPECT() *MockdiffGeneratorMockRecorder {
	return m.recorder
}

// AddDiffAdmins mocks base method.
func (m *MockdiffGenerator) AddDiffAdmins(admins []sls.ListItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDiffAdmins", admins)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDiffAdmins indicates an expected call of AddDiffAdmins.
func (mr *MockdiffGeneratorMockRecorder) AddDiffAdmins(admins any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDiffAdmins", reflect.TypeOf((*MockdiffGenerator)(nil).AddDiffAdmins), admins)
}

// AddDiffQuarantines mocks base method.
func (m *MockdiffGenerator) AddDiffQuarantines(quarantines []*model.Quarantine) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddDiffQuarantines", quarantines)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddDiffQuarantines indicates an expected call of AddDiffQuarantines.
func (mr *MockdiffGeneratorMockRecorder) AddDiffQuarantines(quarantines any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddDiffQuarantines", reflect.TypeOf((*MockdiffGenerator)(nil).AddDiffQuarantines), quarantines)
}

// RemoveDiffAdmins mocks base method.
func (m *MockdiffGenerator) RemoveDiffAdmins(admins []sls.ListItem) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDiffAdmins", admins)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDiffAdmins indicates an expected call of RemoveDiffAdmins.
func (mr *MockdiffGeneratorMockRecorder) RemoveDiffAdmins(admins any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDiffAdmins", reflect.TypeOf((*MockdiffGenerator)(nil).RemoveDiffAdmins), admins)
}

// RemoveDiffQuarantines mocks base method.
func (m *MockdiffGenerator) RemoveDiffQuarantines(txHashes []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveDiffQuarantines", txHashes)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveDiffQuarantines indicates an expected call of RemoveDiffQuarantines.
func (mr *MockdiffGeneratorMockRecorder) RemoveDiffQuarantines(txHashes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveDiffQuarantines", reflect.TypeOf((*MockdiffGenerator)(nil).RemoveDiffQuarantines), txHashes)
}

// MocksnapshotGenerator is a mock of snapshotGenerator interface.
type MocksnapshotGenerator struct {
	ctrl     *gomock.Controller
	recorder *MocksnapshotGeneratorMockRecorder
	isgomock struct{}
}

// MocksnapshotGeneratorMockRecorder is the mock recorder for MocksnapshotGenerator.
type MocksnapshotGeneratorMockRecorder struct {
	mock *MocksnapshotGenerator
}

// NewMocksnapshotGenerator creates a new mock instance.
func NewMocksnapshotGenerator(ctrl *gomock.Controller) *MocksnapshotGenerator {
	mock := &MocksnapshotGenerator{ctrl: ctrl}
	mock.recorder = &MocksnapshotGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksnapshotGenerator) EXPECT() *MocksnapshotGeneratorMockRecorder {
	return m.recorder
}

// TakeNewSnapshot mocks base method.
func (m *MocksnapshotGenerator) TakeNewSnapshot(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TakeNewSnapshot", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// TakeNewSnapshot indicates an expected call of TakeNewSnapshot.
func (mr *MocksnapshotGeneratorMockRecorder) TakeNewSnapshot(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TakeNewSnapshot", reflect.TypeOf((*MocksnapshotGenerator)(nil).TakeNewSnapshot), ctx)
}
