// Code generated by MockGen. DO NOT EDIT.
// Source: snapshot_generator.go
//
// Generated by this command:
//
//	mockgen -source snapshot_generator.go -destination mock_sls_store.go -package slsstray
//

// Package slsstray is a generated GoMock package.
package slsstray

import (
	context "context"
	reflect "reflect"

	common "github.com/zircuit-labs/l2-geth/common"
	model "github.com/zircuit-labs/l2-geth/core/sls-common/model"
	pg "github.com/zircuit-labs/zkr-go-common/stores/pg"
	gomock "go.uber.org/mock/gomock"
)

// MockslsStore is a mock of slsStore interface.
type MockslsStore struct {
	ctrl     *gomock.Controller
	recorder *MockslsStoreMockRecorder
	isgomock struct{}
}

// MockslsStoreMockRecorder is the mock recorder for MockslsStore.
type MockslsStoreMockRecorder struct {
	mock *MockslsStore
}

// NewMockslsStore creates a new mock instance.
func NewMockslsStore(ctrl *gomock.Controller) *MockslsStore {
	mock := &MockslsStore{ctrl: ctrl}
	mock.recorder = &MockslsStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockslsStore) EXPECT() *MockslsStoreMockRecorder {
	return m.recorder
}

// AdminAddresses mocks base method.
func (m *MockslsStore) AdminAddresses(ctx context.Context, opts pg.QueryOpts) ([]*model.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminAddresses", ctx, opts)
	ret0, _ := ret[0].([]*model.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminAddresses indicates an expected call of AdminAddresses.
func (mr *MockslsStoreMockRecorder) AdminAddresses(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminAddresses", reflect.TypeOf((*MockslsStore)(nil).AdminAddresses), ctx, opts)
}

// Quarantined mocks base method.
func (m *MockslsStore) Quarantined(ctx context.Context, opts pg.QueryOpts, from *common.Address) (pg.Cursor, []*model.Quarantine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Quarantined", ctx, opts, from)
	ret0, _ := ret[0].(pg.Cursor)
	ret1, _ := ret[1].([]*model.Quarantine)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Quarantined indicates an expected call of Quarantined.
func (mr *MockslsStoreMockRecorder) Quarantined(ctx, opts, from any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Quarantined", reflect.TypeOf((*MockslsStore)(nil).Quarantined), ctx, opts, from)
}
