// Code generated by MockGen. DO NOT EDIT.
// Source: merkleroot_store.go
//
// Generated by this command:
//
//	mockgen -source merkleroot_store.go -destination mock_merkleroot_generator.go -package slsstray
//

// Package slsstray is a generated GoMock package.
package slsstray

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockmerkleRootGenerator is a mock of merkleRootGenerator interface.
type MockmerkleRootGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockmerkleRootGeneratorMockRecorder
	isgomock struct{}
}

// MockmerkleRootGeneratorMockRecorder is the mock recorder for MockmerkleRootGenerator.
type MockmerkleRootGeneratorMockRecorder struct {
	mock *MockmerkleRootGenerator
}

// NewMockmerkleRootGenerator creates a new mock instance.
func NewMockmerkleRootGenerator(ctrl *gomock.Controller) *MockmerkleRootGenerator {
	mock := &MockmerkleRootGenerator{ctrl: ctrl}
	mock.recorder = &MockmerkleRootGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockmerkleRootGenerator) EXPECT() *MockmerkleRootGeneratorMockRecorder {
	return m.recorder
}

// GetMerkleRoot mocks base method.
func (m *MockmerkleRootGenerator) GetMerkleRoot() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMerkleRoot")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetMerkleRoot indicates an expected call of GetMerkleRoot.
func (mr *MockmerkleRootGeneratorMockRecorder) GetMerkleRoot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMerkleRoot", reflect.TypeOf((*MockmerkleRootGenerator)(nil).GetMerkleRoot))
}
