// Code generated by MockGen. DO NOT EDIT.
// Source: slsdata_syncer.go
//
// Generated by this command:
//
//	mockgen -source slsdata_syncer.go -destination s3_store_mock.go -package slsstray
//

// Package slsstray is a generated GoMock package.
package slsstray

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mocks3Store is a mock of s3Store interface.
type Mocks3Store struct {
	ctrl     *gomock.Controller
	recorder *Mocks3StoreMockRecorder
	isgomock struct{}
}

// Mocks3StoreMockRecorder is the mock recorder for Mocks3Store.
type Mocks3StoreMockRecorder struct {
	mock *Mocks3Store
}

// NewMocks3Store creates a new mock instance.
func NewMocks3Store(ctrl *gomock.Controller) *Mocks3Store {
	mock := &Mocks3Store{ctrl: ctrl}
	mock.recorder = &Mocks3StoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mocks3Store) EXPECT() *Mocks3StoreMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *Mocks3Store) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *Mocks3StoreMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*Mocks3Store)(nil).Delete), ctx, key)
}

// Exists mocks base method.
func (m *Mocks3Store) Exists(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Exists indicates an expected call of Exists.
func (mr *Mocks3StoreMockRecorder) Exists(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*Mocks3Store)(nil).Exists), ctx, key)
}

// Get mocks base method.
func (m *Mocks3Store) Get(ctx context.Context, key string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *Mocks3StoreMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*Mocks3Store)(nil).Get), ctx, key)
}

// GetAllList mocks base method.
func (m *Mocks3Store) GetAllList(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllList", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllList indicates an expected call of GetAllList.
func (mr *Mocks3StoreMockRecorder) GetAllList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllList", reflect.TypeOf((*Mocks3Store)(nil).GetAllList), ctx)
}

// GetBucket mocks base method.
func (m *Mocks3Store) GetBucket() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBucket")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBucket indicates an expected call of GetBucket.
func (mr *Mocks3StoreMockRecorder) GetBucket() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBucket", reflect.TypeOf((*Mocks3Store)(nil).GetBucket))
}

// SetBucket mocks base method.
func (m *Mocks3Store) SetBucket(bucket string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetBucket", bucket)
}

// SetBucket indicates an expected call of SetBucket.
func (mr *Mocks3StoreMockRecorder) SetBucket(bucket any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetBucket", reflect.TypeOf((*Mocks3Store)(nil).SetBucket), bucket)
}

// Upload mocks base method.
func (m *Mocks3Store) Upload(ctx context.Context, key string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, key, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *Mocks3StoreMockRecorder) Upload(ctx, key, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*Mocks3Store)(nil).Upload), ctx, key, data)
}
