// Code generated by MockGen. DO NOT EDIT.
// Source: worker.go
//
// Generated by this command:
//
//	mockgen -source worker.go -destination mock_worker.go -package sls
//

// Package sls is a generated GoMock package.
package sls

import (
	context "context"
	reflect "reflect"

	common "github.com/zircuit-labs/l2-geth/common"
	types "github.com/zircuit-labs/l2-geth/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockWorker is a mock of Worker interface.
type MockWorker struct {
	ctrl     *gomock.Controller
	recorder *MockWorkerMockRecorder
	isgomock struct{}
}

// MockWorkerMockRecorder is the mock recorder for MockWorker.
type MockWorkerMockRecorder struct {
	mock *MockWorker
}

// NewMockWorker creates a new mock instance.
func NewMockWorker(ctrl *gomock.Controller) *MockWorker {
	mock := &MockWorker{ctrl: ctrl}
	mock.recorder = &MockWorkerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorker) EXPECT() *MockWorkerMockRecorder {
	return m.recorder
}

// ValidateBlock mocks base method.
func (m *MockWorker) ValidateBlock(ctx context.Context, depositTxs types.Transactions, block *types.Block, blockTrace *types.BlockTrace) ([]common.Hash, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateBlock", ctx, depositTxs, block, blockTrace)
	ret0, _ := ret[0].([]common.Hash)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateBlock indicates an expected call of ValidateBlock.
func (mr *MockWorkerMockRecorder) ValidateBlock(ctx, depositTxs, block, blockTrace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateBlock", reflect.TypeOf((*MockWorker)(nil).ValidateBlock), ctx, depositTxs, block, blockTrace)
}

// MockTransactionClassifier is a mock of TransactionClassifier interface.
type MockTransactionClassifier struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionClassifierMockRecorder
	isgomock struct{}
}

// MockTransactionClassifierMockRecorder is the mock recorder for MockTransactionClassifier.
type MockTransactionClassifierMockRecorder struct {
	mock *MockTransactionClassifier
}

// NewMockTransactionClassifier creates a new mock instance.
func NewMockTransactionClassifier(ctrl *gomock.Controller) *MockTransactionClassifier {
	mock := &MockTransactionClassifier{ctrl: ctrl}
	mock.recorder = &MockTransactionClassifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionClassifier) EXPECT() *MockTransactionClassifierMockRecorder {
	return m.recorder
}

// Classify mocks base method.
func (m *MockTransactionClassifier) Classify(depositTxs, flaggedTxs types.Transactions) ([]common.Hash, []common.Hash) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Classify", depositTxs, flaggedTxs)
	ret0, _ := ret[0].([]common.Hash)
	ret1, _ := ret[1].([]common.Hash)
	return ret0, ret1
}

// Classify indicates an expected call of Classify.
func (mr *MockTransactionClassifierMockRecorder) Classify(depositTxs, flaggedTxs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Classify", reflect.TypeOf((*MockTransactionClassifier)(nil).Classify), depositTxs, flaggedTxs)
}
