// Code generated by MockGen. DO NOT EDIT.
// Source: quarantiner.go
//
// Generated by this command:
//
//	mockgen -source quarantiner.go -destination mock_quarantiner.go -package sls
//

// Package sls is a generated GoMock package.
package sls

import (
	context "context"
	reflect "reflect"

	common "github.com/zircuit-labs/l2-geth/common"
	model "github.com/zircuit-labs/l2-geth/core/sls-common/model"
	types "github.com/zircuit-labs/l2-geth/core/types"
	pg "github.com/zircuit-labs/zkr-go-common/stores/pg"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockStorage) Add(ctx context.Context, quarantine *model.Quarantine) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, quarantine)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockStorageMockRecorder) Add(ctx, quarantine any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockStorage)(nil).Add), ctx, quarantine)
}

// AddMany mocks base method.
func (m *MockStorage) AddMany(ctx context.Context, quarantines []*model.Quarantine) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMany", ctx, quarantines)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddMany indicates an expected call of AddMany.
func (mr *MockStorageMockRecorder) AddMany(ctx, quarantines any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMany", reflect.TypeOf((*MockStorage)(nil).AddMany), ctx, quarantines)
}

// AdminAddresses mocks base method.
func (m *MockStorage) AdminAddresses(ctx context.Context, opts pg.QueryOpts) ([]*model.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminAddresses", ctx, opts)
	ret0, _ := ret[0].([]*model.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminAddresses indicates an expected call of AdminAddresses.
func (mr *MockStorageMockRecorder) AdminAddresses(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminAddresses", reflect.TypeOf((*MockStorage)(nil).AdminAddresses), ctx, opts)
}

// PendingRelease mocks base method.
func (m *MockStorage) PendingRelease(ctx context.Context, quarantineTypes []model.QuarantineType) ([]*model.Quarantine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingRelease", ctx, quarantineTypes)
	ret0, _ := ret[0].([]*model.Quarantine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PendingRelease indicates an expected call of PendingRelease.
func (mr *MockStorageMockRecorder) PendingRelease(ctx, quarantineTypes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingRelease", reflect.TypeOf((*MockStorage)(nil).PendingRelease), ctx, quarantineTypes)
}

// Quarantined mocks base method.
func (m *MockStorage) Quarantined(ctx context.Context, opts pg.QueryOpts, from *common.Address) (pg.Cursor, []*model.Quarantine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Quarantined", ctx, opts, from)
	ret0, _ := ret[0].(pg.Cursor)
	ret1, _ := ret[1].([]*model.Quarantine)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Quarantined indicates an expected call of Quarantined.
func (mr *MockStorageMockRecorder) Quarantined(ctx, opts, from any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Quarantined", reflect.TypeOf((*MockStorage)(nil).Quarantined), ctx, opts, from)
}

// Release mocks base method.
func (m *MockStorage) Release(ctx context.Context, txHash common.Hash, reason string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, txHash, reason)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Release indicates an expected call of Release.
func (mr *MockStorageMockRecorder) Release(ctx, txHash, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockStorage)(nil).Release), ctx, txHash, reason)
}

// MockQuarantiner is a mock of Quarantiner interface.
type MockQuarantiner struct {
	ctrl     *gomock.Controller
	recorder *MockQuarantinerMockRecorder
	isgomock struct{}
}

// MockQuarantinerMockRecorder is the mock recorder for MockQuarantiner.
type MockQuarantinerMockRecorder struct {
	mock *MockQuarantiner
}

// NewMockQuarantiner creates a new mock instance.
func NewMockQuarantiner(ctrl *gomock.Controller) *MockQuarantiner {
	mock := &MockQuarantiner{ctrl: ctrl}
	mock.recorder = &MockQuarantinerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuarantiner) EXPECT() *MockQuarantinerMockRecorder {
	return m.recorder
}

// PendingRelease mocks base method.
func (m *MockQuarantiner) PendingRelease(ctx context.Context, quarantineTypes []model.QuarantineType) ([]*model.Quarantine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PendingRelease", ctx, quarantineTypes)
	ret0, _ := ret[0].([]*model.Quarantine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PendingRelease indicates an expected call of PendingRelease.
func (mr *MockQuarantinerMockRecorder) PendingRelease(ctx, quarantineTypes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PendingRelease", reflect.TypeOf((*MockQuarantiner)(nil).PendingRelease), ctx, quarantineTypes)
}

// Release mocks base method.
func (m *MockQuarantiner) Release(ctx context.Context, transaction *types.Transaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, transaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockQuarantinerMockRecorder) Release(ctx, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockQuarantiner)(nil).Release), ctx, transaction)
}

// SendManyToQuarantine mocks base method.
func (m *MockQuarantiner) SendManyToQuarantine(ctx context.Context, transactions []QuarantinedTransaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendManyToQuarantine", ctx, transactions)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendManyToQuarantine indicates an expected call of SendManyToQuarantine.
func (mr *MockQuarantinerMockRecorder) SendManyToQuarantine(ctx, transactions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendManyToQuarantine", reflect.TypeOf((*MockQuarantiner)(nil).SendManyToQuarantine), ctx, transactions)
}

// SendToQuarantine mocks base method.
func (m *MockQuarantiner) SendToQuarantine(ctx context.Context, transaction *types.Transaction, quarantineType model.QuarantineType, detector, reason string, loss uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendToQuarantine", ctx, transaction, quarantineType, detector, reason, loss)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendToQuarantine indicates an expected call of SendToQuarantine.
func (mr *MockQuarantinerMockRecorder) SendToQuarantine(ctx, transaction, quarantineType, detector, reason, loss any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendToQuarantine", reflect.TypeOf((*MockQuarantiner)(nil).SendToQuarantine), ctx, transaction, quarantineType, detector, reason, loss)
}

// WasRecentlyQuarantined mocks base method.
func (m *MockQuarantiner) WasRecentlyQuarantined(txHash string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WasRecentlyQuarantined", txHash)
	ret0, _ := ret[0].(bool)
	return ret0
}

// WasRecentlyQuarantined indicates an expected call of WasRecentlyQuarantined.
func (mr *MockQuarantinerMockRecorder) WasRecentlyQuarantined(txHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WasRecentlyQuarantined", reflect.TypeOf((*MockQuarantiner)(nil).WasRecentlyQuarantined), txHash)
}
