// Code generated by MockGen. DO NOT EDIT.
// Source: txprocessor.go
//
// Generated by this command:
//
//	mockgen -source txprocessor.go -destination mock_txprocessor.go -package sls
//

// Package sls is a generated GoMock package.
package sls

import (
	context "context"
	reflect "reflect"

	common "github.com/zircuit-labs/l2-geth/common"
	types "github.com/zircuit-labs/l2-geth/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockTXProcessor is a mock of TXProcessor interface.
type MockTXProcessor struct {
	ctrl     *gomock.Controller
	recorder *MockTXProcessorMockRecorder
	isgomock struct{}
}

// MockTXProcessorMockRecorder is the mock recorder for MockTXProcessor.
type MockTXProcessorMockRecorder struct {
	mock *MockTXProcessor
}

// NewMockTXProcessor creates a new mock instance.
func NewMockTXProcessor(ctrl *gomock.Controller) *MockTXProcessor {
	mock := &MockTXProcessor{ctrl: ctrl}
	mock.recorder = &MockTXProcessorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTXProcessor) EXPECT() *MockTXProcessorMockRecorder {
	return m.recorder
}

// Awaited mocks base method.
func (m *MockTXProcessor) Awaited(addr common.Address) types.Transactions {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Awaited", addr)
	ret0, _ := ret[0].(types.Transactions)
	return ret0
}

// Awaited indicates an expected call of Awaited.
func (mr *MockTXProcessorMockRecorder) Awaited(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Awaited", reflect.TypeOf((*MockTXProcessor)(nil).Awaited), addr)
}

// CollectAllPromotables mocks base method.
func (m *MockTXProcessor) CollectAllPromotables() types.Transactions {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectAllPromotables")
	ret0, _ := ret[0].(types.Transactions)
	return ret0
}

// CollectAllPromotables indicates an expected call of CollectAllPromotables.
func (mr *MockTXProcessorMockRecorder) CollectAllPromotables() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectAllPromotables", reflect.TypeOf((*MockTXProcessor)(nil).CollectAllPromotables))
}

// CollectQuarantinedAddresses mocks base method.
func (m *MockTXProcessor) CollectQuarantinedAddresses() []common.Address {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectQuarantinedAddresses")
	ret0, _ := ret[0].([]common.Address)
	return ret0
}

// CollectQuarantinedAddresses indicates an expected call of CollectQuarantinedAddresses.
func (mr *MockTXProcessorMockRecorder) CollectQuarantinedAddresses() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectQuarantinedAddresses", reflect.TypeOf((*MockTXProcessor)(nil).CollectQuarantinedAddresses))
}

// CollectSendBackToPool mocks base method.
func (m *MockTXProcessor) CollectSendBackToPool() types.Transactions {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CollectSendBackToPool")
	ret0, _ := ret[0].(types.Transactions)
	return ret0
}

// CollectSendBackToPool indicates an expected call of CollectSendBackToPool.
func (mr *MockTXProcessorMockRecorder) CollectSendBackToPool() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CollectSendBackToPool", reflect.TypeOf((*MockTXProcessor)(nil).CollectSendBackToPool))
}

// IsAddressWaiting mocks base method.
func (m *MockTXProcessor) IsAddressWaiting(addr common.Address) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAddressWaiting", addr)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsAddressWaiting indicates an expected call of IsAddressWaiting.
func (mr *MockTXProcessorMockRecorder) IsAddressWaiting(addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAddressWaiting", reflect.TypeOf((*MockTXProcessor)(nil).IsAddressWaiting), addr)
}

// ProcessTransactions mocks base method.
func (m *MockTXProcessor) ProcessTransactions(ctx context.Context, addr common.Address, transactions types.Transactions) types.Transactions {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessTransactions", ctx, addr, transactions)
	ret0, _ := ret[0].(types.Transactions)
	return ret0
}

// ProcessTransactions indicates an expected call of ProcessTransactions.
func (mr *MockTXProcessorMockRecorder) ProcessTransactions(ctx, addr, transactions any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessTransactions", reflect.TypeOf((*MockTXProcessor)(nil).ProcessTransactions), ctx, addr, transactions)
}

// Stop mocks base method.
func (m *MockTXProcessor) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockTXProcessorMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockTXProcessor)(nil).Stop))
}

// MockEventSender is a mock of EventSender interface.
type MockEventSender struct {
	ctrl     *gomock.Controller
	recorder *MockEventSenderMockRecorder
	isgomock struct{}
}

// MockEventSenderMockRecorder is the mock recorder for MockEventSender.
type MockEventSenderMockRecorder struct {
	mock *MockEventSender
}

// NewMockEventSender creates a new mock instance.
func NewMockEventSender(ctrl *gomock.Controller) *MockEventSender {
	mock := &MockEventSender{ctrl: ctrl}
	mock.recorder = &MockEventSenderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventSender) EXPECT() *MockEventSenderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockEventSender) Send(value any) int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", value)
	ret0, _ := ret[0].(int)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockEventSenderMockRecorder) Send(value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockEventSender)(nil).Send), value)
}

// MockLegacyPool is a mock of LegacyPool interface.
type MockLegacyPool[CFG any, R any] struct {
	ctrl     *gomock.Controller
	recorder *MockLegacyPoolMockRecorder[CFG, R]
	isgomock struct{}
}

// MockLegacyPoolMockRecorder is the mock recorder for MockLegacyPool.
type MockLegacyPoolMockRecorder[CFG any, R any] struct {
	mock *MockLegacyPool[CFG, R]
}

// NewMockLegacyPool creates a new mock instance.
func NewMockLegacyPool[CFG any, R any](ctrl *gomock.Controller) *MockLegacyPool[CFG, R] {
	mock := &MockLegacyPool[CFG, R]{ctrl: ctrl}
	mock.recorder = &MockLegacyPoolMockRecorder[CFG, R]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLegacyPool[CFG, R]) EXPECT() *MockLegacyPoolMockRecorder[CFG, R] {
	return m.recorder
}

// DetectorManager mocks base method.
func (m *MockLegacyPool[CFG, R]) DetectorManager() DetectorManager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetectorManager")
	ret0, _ := ret[0].(DetectorManager)
	return ret0
}

// DetectorManager indicates an expected call of DetectorManager.
func (mr *MockLegacyPoolMockRecorder[CFG, R]) DetectorManager() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetectorManager", reflect.TypeOf((*MockLegacyPool[CFG, R])(nil).DetectorManager))
}

// GetSLSRefreshables mocks base method.
func (m *MockLegacyPool[CFG, R]) GetSLSRefreshables() R {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSLSRefreshables")
	ret0, _ := ret[0].(R)
	return ret0
}

// GetSLSRefreshables indicates an expected call of GetSLSRefreshables.
func (mr *MockLegacyPoolMockRecorder[CFG, R]) GetSLSRefreshables() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSLSRefreshables", reflect.TypeOf((*MockLegacyPool[CFG, R])(nil).GetSLSRefreshables))
}

// PromoteTx mocks base method.
func (m *MockLegacyPool[CFG, R]) PromoteTx(addr common.Address, hash common.Hash, tx *types.Transaction) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromoteTx", addr, hash, tx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// PromoteTx indicates an expected call of PromoteTx.
func (mr *MockLegacyPoolMockRecorder[CFG, R]) PromoteTx(addr, hash, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromoteTx", reflect.TypeOf((*MockLegacyPool[CFG, R])(nil).PromoteTx), addr, hash, tx)
}

// Quarantiner mocks base method.
func (m *MockLegacyPool[CFG, R]) Quarantiner() Quarantiner {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Quarantiner")
	ret0, _ := ret[0].(Quarantiner)
	return ret0
}

// Quarantiner indicates an expected call of Quarantiner.
func (mr *MockLegacyPoolMockRecorder[CFG, R]) Quarantiner() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Quarantiner", reflect.TypeOf((*MockLegacyPool[CFG, R])(nil).Quarantiner))
}

// SLSConfig mocks base method.
func (m *MockLegacyPool[CFG, R]) SLSConfig() CFG {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SLSConfig")
	ret0, _ := ret[0].(CFG)
	return ret0
}

// SLSConfig indicates an expected call of SLSConfig.
func (mr *MockLegacyPoolMockRecorder[CFG, R]) SLSConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SLSConfig", reflect.TypeOf((*MockLegacyPool[CFG, R])(nil).SLSConfig))
}

// TxFeed mocks base method.
func (m *MockLegacyPool[CFG, R]) TxFeed() EventSender {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TxFeed")
	ret0, _ := ret[0].(EventSender)
	return ret0
}

// TxFeed indicates an expected call of TxFeed.
func (mr *MockLegacyPoolMockRecorder[CFG, R]) TxFeed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TxFeed", reflect.TypeOf((*MockLegacyPool[CFG, R])(nil).TxFeed))
}
