// Code generated by MockGen. DO NOT EDIT.
// Source: manager.go
//
// Generated by this command:
//
//	mockgen -source manager.go -destination mock_manager.go -package sls
//

// Package sls is a generated GoMock package.
package sls

import (
	context "context"
	reflect "reflect"

	types "github.com/zircuit-labs/l2-geth/core/types"
	gomock "go.uber.org/mock/gomock"
)

// MockDetectorManager is a mock of DetectorManager interface.
type MockDetectorManager struct {
	ctrl     *gomock.Controller
	recorder *MockDetectorManagerMockRecorder
	isgomock struct{}
}

// MockDetectorManagerMockRecorder is the mock recorder for MockDetectorManager.
type MockDetectorManagerMockRecorder struct {
	mock *MockDetectorManager
}

// NewMockDetectorManager creates a new mock instance.
func NewMockDetectorManager(ctrl *gomock.Controller) *MockDetectorManager {
	mock := &MockDetectorManager{ctrl: ctrl}
	mock.recorder = &MockDetectorManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDetectorManager) EXPECT() *MockDetectorManagerMockRecorder {
	return m.recorder
}

// DetectQuarantinableTransactionsInBlock mocks base method.
func (m *MockDetectorManager) DetectQuarantinableTransactionsInBlock(ctx context.Context, block *types.Block, blockTrace *types.BlockTrace) ([]QuarantinedTransactionFromBlock, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetectQuarantinableTransactionsInBlock", ctx, block, blockTrace)
	ret0, _ := ret[0].([]QuarantinedTransactionFromBlock)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DetectQuarantinableTransactionsInBlock indicates an expected call of DetectQuarantinableTransactionsInBlock.
func (mr *MockDetectorManagerMockRecorder) DetectQuarantinableTransactionsInBlock(ctx, block, blockTrace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetectQuarantinableTransactionsInBlock", reflect.TypeOf((*MockDetectorManager)(nil).DetectQuarantinableTransactionsInBlock), ctx, block, blockTrace)
}

// IsTrusted mocks base method.
func (m *MockDetectorManager) IsTrusted(ctx context.Context, tx *types.Transaction) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTrusted", ctx, tx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsTrusted indicates an expected call of IsTrusted.
func (mr *MockDetectorManagerMockRecorder) IsTrusted(ctx, tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTrusted", reflect.TypeOf((*MockDetectorManager)(nil).IsTrusted), ctx, tx)
}

// RecordBlockTransactionResults mocks base method.
func (m *MockDetectorManager) RecordBlockTransactionResults(ctx context.Context, block *types.Block, flaggedTxs []QuarantinedTransactionFromBlock) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordBlockTransactionResults", ctx, block, flaggedTxs)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordBlockTransactionResults indicates an expected call of RecordBlockTransactionResults.
func (mr *MockDetectorManagerMockRecorder) RecordBlockTransactionResults(ctx, block, flaggedTxs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordBlockTransactionResults", reflect.TypeOf((*MockDetectorManager)(nil).RecordBlockTransactionResults), ctx, block, flaggedTxs)
}

// ShouldBeQuarantined mocks base method.
func (m *MockDetectorManager) ShouldBeQuarantined(ctx context.Context, tx *types.Transaction, detectorType DetectorType) (ManagerResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldBeQuarantined", ctx, tx, detectorType)
	ret0, _ := ret[0].(ManagerResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShouldBeQuarantined indicates an expected call of ShouldBeQuarantined.
func (mr *MockDetectorManagerMockRecorder) ShouldBeQuarantined(ctx, tx, detectorType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldBeQuarantined", reflect.TypeOf((*MockDetectorManager)(nil).ShouldBeQuarantined), ctx, tx, detectorType)
}

// Stop mocks base method.
func (m *MockDetectorManager) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockDetectorManagerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockDetectorManager)(nil).Stop))
}

// MockTransactionDetector is a mock of TransactionDetector interface.
type MockTransactionDetector struct {
	ctrl     *gomock.Controller
	recorder *MockTransactionDetectorMockRecorder
	isgomock struct{}
}

// MockTransactionDetectorMockRecorder is the mock recorder for MockTransactionDetector.
type MockTransactionDetectorMockRecorder struct {
	mock *MockTransactionDetector
}

// NewMockTransactionDetector creates a new mock instance.
func NewMockTransactionDetector(ctrl *gomock.Controller) *MockTransactionDetector {
	mock := &MockTransactionDetector{ctrl: ctrl}
	mock.recorder = &MockTransactionDetectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTransactionDetector) EXPECT() *MockTransactionDetectorMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockTransactionDetector) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockTransactionDetectorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockTransactionDetector)(nil).Name))
}

// ShouldBeQuarantined mocks base method.
func (m *MockTransactionDetector) ShouldBeQuarantined(ctx context.Context, transaction *types.Transaction) (bool, string, uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldBeQuarantined", ctx, transaction)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(uint64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// ShouldBeQuarantined indicates an expected call of ShouldBeQuarantined.
func (mr *MockTransactionDetectorMockRecorder) ShouldBeQuarantined(ctx, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldBeQuarantined", reflect.TypeOf((*MockTransactionDetector)(nil).ShouldBeQuarantined), ctx, transaction)
}

// Stop mocks base method.
func (m *MockTransactionDetector) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockTransactionDetectorMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockTransactionDetector)(nil).Stop))
}

// MockBlockDetector is a mock of BlockDetector interface.
type MockBlockDetector struct {
	ctrl     *gomock.Controller
	recorder *MockBlockDetectorMockRecorder
	isgomock struct{}
}

// MockBlockDetectorMockRecorder is the mock recorder for MockBlockDetector.
type MockBlockDetectorMockRecorder struct {
	mock *MockBlockDetector
}

// NewMockBlockDetector creates a new mock instance.
func NewMockBlockDetector(ctrl *gomock.Controller) *MockBlockDetector {
	mock := &MockBlockDetector{ctrl: ctrl}
	mock.recorder = &MockBlockDetectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlockDetector) EXPECT() *MockBlockDetectorMockRecorder {
	return m.recorder
}

// DetectQuarantinableTransactions mocks base method.
func (m *MockBlockDetector) DetectQuarantinableTransactions(ctx context.Context, block *types.Block, blockTrace *types.BlockTrace) (types.Transactions, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DetectQuarantinableTransactions", ctx, block, blockTrace)
	ret0, _ := ret[0].(types.Transactions)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// DetectQuarantinableTransactions indicates an expected call of DetectQuarantinableTransactions.
func (mr *MockBlockDetectorMockRecorder) DetectQuarantinableTransactions(ctx, block, blockTrace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DetectQuarantinableTransactions", reflect.TypeOf((*MockBlockDetector)(nil).DetectQuarantinableTransactions), ctx, block, blockTrace)
}

// Name mocks base method.
func (m *MockBlockDetector) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockBlockDetectorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockBlockDetector)(nil).Name))
}

// Stop mocks base method.
func (m *MockBlockDetector) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockBlockDetectorMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockBlockDetector)(nil).Stop))
}

// MockTrustVerifier is a mock of TrustVerifier interface.
type MockTrustVerifier struct {
	ctrl     *gomock.Controller
	recorder *MockTrustVerifierMockRecorder
	isgomock struct{}
}

// MockTrustVerifierMockRecorder is the mock recorder for MockTrustVerifier.
type MockTrustVerifierMockRecorder struct {
	mock *MockTrustVerifier
}

// NewMockTrustVerifier creates a new mock instance.
func NewMockTrustVerifier(ctrl *gomock.Controller) *MockTrustVerifier {
	mock := &MockTrustVerifier{ctrl: ctrl}
	mock.recorder = &MockTrustVerifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTrustVerifier) EXPECT() *MockTrustVerifierMockRecorder {
	return m.recorder
}

// IsTrustable mocks base method.
func (m *MockTrustVerifier) IsTrustable(ctx context.Context, transaction *types.Transaction) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsTrustable", ctx, transaction)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsTrustable indicates an expected call of IsTrustable.
func (mr *MockTrustVerifierMockRecorder) IsTrustable(ctx, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsTrustable", reflect.TypeOf((*MockTrustVerifier)(nil).IsTrustable), ctx, transaction)
}

// Name mocks base method.
func (m *MockTrustVerifier) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockTrustVerifierMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockTrustVerifier)(nil).Name))
}
