// Code generated by MockGen. DO NOT EDIT.
// Source: blob.go
//
// Generated by this command:
//
//	mockgen -source blob.go -destination mock_blocb.go -package storage
//

// Package storage is a generated GoMock package.
package storage

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockS3Storer is a mock of S3Storer interface.
type MockS3Storer struct {
	ctrl     *gomock.Controller
	recorder *MockS3StorerMockRecorder
	isgomock struct{}
}

// MockS3StorerMockRecorder is the mock recorder for MockS3Storer.
type MockS3StorerMockRecorder struct {
	mock *MockS3Storer
}

// NewMockS3Storer creates a new mock instance.
func NewMockS3Storer(ctrl *gomock.Controller) *MockS3Storer {
	mock := &MockS3Storer{ctrl: ctrl}
	mock.recorder = &MockS3StorerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3Storer) EXPECT() *MockS3StorerMockRecorder {
	return m.recorder
}

// Upload mocks base method.
func (m *MockS3Storer) Upload(ctx context.Context, key string, data []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upload", ctx, key, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upload indicates an expected call of Upload.
func (mr *MockS3StorerMockRecorder) Upload(ctx, key, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upload", reflect.TypeOf((*MockS3Storer)(nil).Upload), ctx, key, data)
}
