// Code generated by MockGen. DO NOT EDIT.
// Source: zircadmin_public.go
//
// Generated by this command:
//
//	mockgen -source zircadmin_public.go -destination mock_zircadmin_public.go -package slsapi
//

// Package slsapi is a generated GoMock package.
package slsapi

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockPayloadFormatter is a mock of PayloadFormatter interface.
type MockPayloadFormatter struct {
	ctrl     *gomock.Controller
	recorder *MockPayloadFormatterMockRecorder
	isgomock struct{}
}

// MockPayloadFormatterMockRecorder is the mock recorder for MockPayloadFormatter.
type MockPayloadFormatterMockRecorder struct {
	mock *MockPayloadFormatter
}

// NewMockPayloadFormatter creates a new mock instance.
func NewMockPayloadFormatter(ctrl *gomock.Controller) *MockPayloadFormatter {
	mock := &MockPayloadFormatter{ctrl: ctrl}
	mock.recorder = &MockPayloadFormatterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPayloadFormatter) EXPECT() *MockPayloadFormatterMockRecorder {
	return m.recorder
}

// Format mocks base method.
func (m *MockPayloadFormatter) Format(currTime time.Time, method string, args []any) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Format", currTime, method, args)
	ret0, _ := ret[0].(string)
	return ret0
}

// Format indicates an expected call of Format.
func (mr *MockPayloadFormatterMockRecorder) Format(currTime, method, args any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Format", reflect.TypeOf((*MockPayloadFormatter)(nil).Format), currTime, method, args)
}
