// Code generated by MockGen. DO NOT EDIT.
// Source: zirc.go
//
// Generated by this command:
//
//	mockgen -source zirc.go -destination mock_zirc.go -package slsapi
//

// Package slsapi is a generated GoMock package.
package slsapi

import (
	context "context"
	reflect "reflect"
	time "time"

	common "github.com/zircuit-labs/l2-geth/common"
	model "github.com/zircuit-labs/l2-geth/core/sls-common/model"
	pg "github.com/zircuit-labs/zkr-go-common/stores/pg"
	gomock "go.uber.org/mock/gomock"
)

// MockQuarantineStorage is a mock of QuarantineStorage interface.
type MockQuarantineStorage struct {
	ctrl     *gomock.Controller
	recorder *MockQuarantineStorageMockRecorder
	isgomock struct{}
}

// MockQuarantineStorageMockRecorder is the mock recorder for MockQuarantineStorage.
type MockQuarantineStorageMockRecorder struct {
	mock *MockQuarantineStorage
}

// NewMockQuarantineStorage creates a new mock instance.
func NewMockQuarantineStorage(ctrl *gomock.Controller) *MockQuarantineStorage {
	mock := &MockQuarantineStorage{ctrl: ctrl}
	mock.recorder = &MockQuarantineStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuarantineStorage) EXPECT() *MockQuarantineStorageMockRecorder {
	return m.recorder
}

// AdminAddresses mocks base method.
func (m *MockQuarantineStorage) AdminAddresses(ctx context.Context, opts pg.QueryOpts) ([]*model.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminAddresses", ctx, opts)
	ret0, _ := ret[0].([]*model.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminAddresses indicates an expected call of AdminAddresses.
func (mr *MockQuarantineStorageMockRecorder) AdminAddresses(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminAddresses", reflect.TypeOf((*MockQuarantineStorage)(nil).AdminAddresses), ctx, opts)
}

// All mocks base method.
func (m *MockQuarantineStorage) All(ctx context.Context, opts pg.QueryOpts, from *common.Address) (pg.Cursor, []*model.Quarantine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx, opts, from)
	ret0, _ := ret[0].(pg.Cursor)
	ret1, _ := ret[1].([]*model.Quarantine)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// All indicates an expected call of All.
func (mr *MockQuarantineStorageMockRecorder) All(ctx, opts, from any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockQuarantineStorage)(nil).All), ctx, opts, from)
}

// FindByHash mocks base method.
func (m *MockQuarantineStorage) FindByHash(ctx context.Context, txHash common.Hash) (*model.Quarantine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHash", ctx, txHash)
	ret0, _ := ret[0].(*model.Quarantine)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHash indicates an expected call of FindByHash.
func (mr *MockQuarantineStorageMockRecorder) FindByHash(ctx, txHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHash", reflect.TypeOf((*MockQuarantineStorage)(nil).FindByHash), ctx, txHash)
}

// GetAdminAddresses mocks base method.
func (m *MockQuarantineStorage) GetAdminAddresses(ctx context.Context) ([]common.Address, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAdminAddresses", ctx)
	ret0, _ := ret[0].([]common.Address)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAdminAddresses indicates an expected call of GetAdminAddresses.
func (mr *MockQuarantineStorageMockRecorder) GetAdminAddresses(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAdminAddresses", reflect.TypeOf((*MockQuarantineStorage)(nil).GetAdminAddresses), ctx)
}

// IsAdmin mocks base method.
func (m *MockQuarantineStorage) IsAdmin(ctx context.Context, address common.Address) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAdmin", ctx, address)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAdmin indicates an expected call of IsAdmin.
func (mr *MockQuarantineStorageMockRecorder) IsAdmin(ctx, address any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAdmin", reflect.TypeOf((*MockQuarantineStorage)(nil).IsAdmin), ctx, address)
}

// IsQuarantined mocks base method.
func (m *MockQuarantineStorage) IsQuarantined(ctx context.Context, txHash common.Hash) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsQuarantined", ctx, txHash)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsQuarantined indicates an expected call of IsQuarantined.
func (mr *MockQuarantineStorageMockRecorder) IsQuarantined(ctx, txHash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsQuarantined", reflect.TypeOf((*MockQuarantineStorage)(nil).IsQuarantined), ctx, txHash)
}

// Quarantined mocks base method.
func (m *MockQuarantineStorage) Quarantined(ctx context.Context, opts pg.QueryOpts, from *common.Address) (pg.Cursor, []*model.Quarantine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Quarantined", ctx, opts, from)
	ret0, _ := ret[0].(pg.Cursor)
	ret1, _ := ret[1].([]*model.Quarantine)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Quarantined indicates an expected call of Quarantined.
func (mr *MockQuarantineStorageMockRecorder) Quarantined(ctx, opts, from any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Quarantined", reflect.TypeOf((*MockQuarantineStorage)(nil).Quarantined), ctx, opts, from)
}

// Release mocks base method.
func (m *MockQuarantineStorage) Release(ctx context.Context, txHash common.Hash, reason string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, txHash, reason)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Release indicates an expected call of Release.
func (mr *MockQuarantineStorageMockRecorder) Release(ctx, txHash, reason any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockQuarantineStorage)(nil).Release), ctx, txHash, reason)
}

// SetExpiresOn mocks base method.
func (m *MockQuarantineStorage) SetExpiresOn(ctx context.Context, txHash common.Hash, expiresOn time.Time, releaser common.Address) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetExpiresOn", ctx, txHash, expiresOn, releaser)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetExpiresOn indicates an expected call of SetExpiresOn.
func (mr *MockQuarantineStorageMockRecorder) SetExpiresOn(ctx, txHash, expiresOn, releaser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExpiresOn", reflect.TypeOf((*MockQuarantineStorage)(nil).SetExpiresOn), ctx, txHash, expiresOn, releaser)
}
