// Code generated by MockGen. DO NOT EDIT.
// Source: api.go
//
// Generated by this command:
//
//	mockgen -source api.go -destination mock_api.go -package catalyst
//

// Package catalyst is a generated GoMock package.
package catalyst

import (
	context "context"
	reflect "reflect"

	common "github.com/zircuit-labs/l2-geth/common"
	sls_common "github.com/zircuit-labs/l2-geth/core/sls-common"
	model "github.com/zircuit-labs/l2-geth/core/sls-common/model"
	types "github.com/zircuit-labs/l2-geth/core/types"
	pg "github.com/zircuit-labs/zkr-go-common/stores/pg"
	gomock "go.uber.org/mock/gomock"
)

// MockdetectorManager is a mock of detectorManager interface.
type MockdetectorManager struct {
	ctrl     *gomock.Controller
	recorder *MockdetectorManagerMockRecorder
	isgomock struct{}
}

// MockdetectorManagerMockRecorder is the mock recorder for MockdetectorManager.
type MockdetectorManagerMockRecorder struct {
	mock *MockdetectorManager
}

// NewMockdetectorManager creates a new mock instance.
func NewMockdetectorManager(ctrl *gomock.Controller) *MockdetectorManager {
	mock := &MockdetectorManager{ctrl: ctrl}
	mock.recorder = &MockdetectorManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdetectorManager) EXPECT() *MockdetectorManagerMockRecorder {
	return m.recorder
}

// ShouldBeQuarantined mocks base method.
func (m *MockdetectorManager) ShouldBeQuarantined(arg0 context.Context, arg1 *types.Transaction, arg2 sls_common.DetectorType) (sls_common.ManagerResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldBeQuarantined", arg0, arg1, arg2)
	ret0, _ := ret[0].(sls_common.ManagerResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShouldBeQuarantined indicates an expected call of ShouldBeQuarantined.
func (mr *MockdetectorManagerMockRecorder) ShouldBeQuarantined(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldBeQuarantined", reflect.TypeOf((*MockdetectorManager)(nil).ShouldBeQuarantined), arg0, arg1, arg2)
}

// Stop mocks base method.
func (m *MockdetectorManager) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockdetectorManagerMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockdetectorManager)(nil).Stop))
}

// Mockrejector is a mock of rejector interface.
type Mockrejector struct {
	ctrl     *gomock.Controller
	recorder *MockrejectorMockRecorder
	isgomock struct{}
}

// MockrejectorMockRecorder is the mock recorder for Mockrejector.
type MockrejectorMockRecorder struct {
	mock *Mockrejector
}

// NewMockrejector creates a new mock instance.
func NewMockrejector(ctrl *gomock.Controller) *Mockrejector {
	mock := &Mockrejector{ctrl: ctrl}
	mock.recorder = &MockrejectorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockrejector) EXPECT() *MockrejectorMockRecorder {
	return m.recorder
}

// AdminAddresses mocks base method.
func (m *Mockrejector) AdminAddresses(ctx context.Context, opts pg.QueryOpts) ([]*model.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminAddresses", ctx, opts)
	ret0, _ := ret[0].([]*model.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AdminAddresses indicates an expected call of AdminAddresses.
func (mr *MockrejectorMockRecorder) AdminAddresses(ctx, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminAddresses", reflect.TypeOf((*Mockrejector)(nil).AdminAddresses), ctx, opts)
}

// Quarantined mocks base method.
func (m *Mockrejector) Quarantined(ctx context.Context, opts pg.QueryOpts, from *common.Address) (pg.Cursor, []*model.Quarantine, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Quarantined", ctx, opts, from)
	ret0, _ := ret[0].(pg.Cursor)
	ret1, _ := ret[1].([]*model.Quarantine)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Quarantined indicates an expected call of Quarantined.
func (mr *MockrejectorMockRecorder) Quarantined(ctx, opts, from any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Quarantined", reflect.TypeOf((*Mockrejector)(nil).Quarantined), ctx, opts, from)
}

// RecordRejectedTx mocks base method.
func (m *Mockrejector) RecordRejectedTx(ctx context.Context, transaction *types.Transaction, detector, reason string, loss uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordRejectedTx", ctx, transaction, detector, reason, loss)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordRejectedTx indicates an expected call of RecordRejectedTx.
func (mr *MockrejectorMockRecorder) RecordRejectedTx(ctx, transaction, detector, reason, loss any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordRejectedTx", reflect.TypeOf((*Mockrejector)(nil).RecordRejectedTx), ctx, transaction, detector, reason, loss)
}
