CREATE EXTENSION IF NOT EXISTS citext;

CREATE TABLE sls.admin
(
    address    CITEXT PRIMARY KEY,
    created_on TIMESTAMPTZ NOT NULL DEFAULT now()
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA sls TO slsadmin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA sls TO slsgeth;
GRANT SELECT ON ALL TABLES IN SCHEMA sls TO slsreadonly;
