CREATE TABLE sls.trust_list
(
    address     CITEXT PRIMARY KEY,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA sls TO slsadmin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA sls TO slsgeth;
GRANT SELECT ON ALL TABLES IN SCHEMA sls TO slsreadonly;
