// Code generated by MockGen. DO NOT EDIT.
// Source: metric.go

// Package metrics is a generated GoMock package.
package metrics

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// IncErrorCounter mocks base method.
func (m *MockMetrics) IncErrorCounter() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncErrorCounter")
}

// IncErrorCounter indicates an expected call of IncErrorCounter.
func (mr *MockMetricsMockRecorder) IncErrorCounter() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncErrorCounter", reflect.TypeOf((*MockMetrics)(nil).IncErrorCounter))
}

// IncFallbackCounter mocks base method.
func (m *MockMetrics) IncFallbackCounter(name string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncFallbackCounter", name)
}

// IncFallbackCounter indicates an expected call of IncFallbackCounter.
func (mr *MockMetricsMockRecorder) IncFallbackCounter(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncFallbackCounter", reflect.TypeOf((*MockMetrics)(nil).IncFallbackCounter), name)
}

// SetQuarantineCount mocks base method.
func (m *MockMetrics) SetQuarantineCount(name string, count int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetQuarantineCount", name, count)
}

// SetQuarantineCount indicates an expected call of SetQuarantineCount.
func (mr *MockMetricsMockRecorder) SetQuarantineCount(name, count interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetQuarantineCount", reflect.TypeOf((*MockMetrics)(nil).SetQuarantineCount), name, count)
}
